### ISSUE TITLE
some words don't seem to have spacing at all

### ISSUE THREAD

**Issue by andybrwr** [s3blocks/s3blocks#1]
![screenshot from 2018-05-27 16-21-28](https://user-images.githubusercontent.com/21012310/40590275-207f9122-61ca-11e8-96d3-0445e082ada7.png)

**Comment by ZenithRogue** [comment]
Spacing is a big issue right now. I haven't had time to properly look into it. In text input areas, spaces are overly compensated an appear at the very end.

**Comment by andybrwr** [comment]
okay. i'm trying to find where spacing happens. it looks like it happens around like 2047 or so in bundle.js

**Comment by ZenithRogue** [comment]
man, i should have closed this a while ago
