### ISSUE TITLE
Extension Color Uses Scratch 2.0 Extensions.

### ISSUE THREAD

**Issue by AmazingMech2418** [s3blocks/s3blocks#13]
The ::extension color feature should be changed to the green used currently in the beta and alpha builds.

**Comment by chexbox** [comment]
We're still working on extension, color is the easy part to fix.

**Comment by ZenithRogue** [comment]
Fixed.
```::extension``` is the new color, ```::oldextension``` is the old color (i just liked the way it looked :P)
