### ISSUE TITLE
Input Bubbles are too Small

### ISSUE THREAD

**Issue by chexbox** [s3blocks/s3blocks#3]
s3blocks: ![2018-05-27-170533_145x53_scrot](https://user-images.githubusercontent.com/31783961/40591135-0924af42-61d1-11e8-8dc0-0f1f8311d99e.png)
scratch 3 preview: ![2018-05-27-170912_207x55_scrot](https://user-images.githubusercontent.com/31783961/40591136-093f09f0-61d1-11e8-88d1-6a08969c0a1e.png)

**Comment by ZenithRogue** [comment]
hella done
