### ISSUE TITLE
Drop-down Issues

### ISSUE THREAD

**Issue by chexbox** [s3blocks/s3blocks#5]
S3Blocks: ![2018-05-27-174245_137x43_scrot](https://user-images.githubusercontent.com/31783961/40591378-a126dcbc-61d5-11e8-8a6c-63ead26c50b1.png)

Preview: ![2018-05-27-174301_165x53_scrot](https://user-images.githubusercontent.com/31783961/40591379-a15c8cae-61d5-11e8-90ab-3fdfb50c51ba.png)

The dropdowns should be rounded, need a darker background, and should have a white arrow.

**Comment by ZenithRogue** [comment]
Hey, thanks for adding all these issues! This one might be a bit tricky to fix, and I have been brainstorming for a while. On some blocks the dropdowns are rectangular, while  others are like this. (Ie the create clone of menu) if you have any ideas of how to differentiate, that would be amazing.

**Comment by chexbox** [comment]
Since "( v)" is no longer being used (as of right now), we could use "( v)" / "[ v]" to differ. 

If Scratch does decide to continue using "( v)" we could use "[ rv]" / "[ sv]" representing round or square drop-downs.
